### PR TITLE
Fix the cron prop update

### PR DESCRIPTION
**Pull request by ShirasawaSama**
### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] README update
- [ ] Other (about what?)

### 💡 Background and solution

When the cron expression is updated from outside the component, the input box is not updated.

```js
const Editor: React.FC<{ cron: string, setCron: (it: string) => void }> = ({ cron, setCron }) => {
  const [cronError, setCronError] = useState(false)
  return <Box>
    <Cron cron={cron} setCron={setCron} setCronError={setCronError} isAdmin />
  </Box>
}
```

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Demo in storybook is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] README API section is updated or not needed

### CODE REVIEW

**Review by baymac — APPROVED** [review]
Thanks for catching this 😅 
Lgtm!

**Comment by ShirasawaSama** [comment]
@baymac 

I found that this bug can't be fixed by such modification, which will make `debounce` work abnormally, resulting in the value can't be modified.

**Comment by ShirasawaSama** [comment]
I think a better solution might be to add a key to the `Scheduler` component.

```js
const FC = ({ cron, ...props }) => <Scheduler key={cron} cron={cron} {...props} />
```

**Comment by baymac** [comment]
@ShirasawaSama how will adding a key help?

**Comment by ShirasawaSama** [comment]
> @ShirasawaSama how will adding a key help?

Let users add the `key` prop on the `Scheduler`.

Or I don't think we should update this value inside the component.

State updates should be handled by the user.

Just like the `<input value={text} onChange={e => setText(e.target.value)} />` of React.

**Comment by ShirasawaSama** [comment]
Now, the `Scheduler` is more like an uncontrolled component.

I think it's better to be a controlled component.

**Pull request merged**
